# Generated by Django 4.2.4 on 2023-09-05 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsprofilequestions',
            name='identification',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalsprofilequestions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
